package dev.threadly.knowledge.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;

/**
 * Entity representing an embedding vector for a knowledge base chunk.
 * Embeddings are generated by the AI service and stored for vector similarity search.
 */
@Entity
@Table(name = "kb_embedding", indexes = {
    @Index(name = "idx_embedding_chunk_id", columnList = "chunk_id"),
    @Index(name = "idx_embedding_model", columnList = "embedding_model")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class KbEmbedding {

  /**
   * Unique identifier for the embedding (UUID).
   */
  @Id
  @Column(nullable = false, length = 36)
  private String id;

  /**
   * Reference to the chunk being embedded.
   */
  @Column(nullable = false, length = 36)
  private String chunkId;

  /**
   * Name of the embedding model used (e.g., "voyage-ai-3", "openai-ada", "local-e5").
   */
  @Column(nullable = false, length = 100)
  private String embeddingModel;

  /**
   * Embedding vector as JSON array of floats.
   * Format: [0.123, -0.456, 0.789, ...]
   */
  @Column(nullable = false, columnDefinition = "TEXT")
  private String embeddingJson;

  /**
   * Dimension of the embedding vector (e.g., 1536 for OpenAI, 1024 for Voyage).
   */
  @Column(nullable = false)
  private Integer dimension;

  /**
   * Timestamp when embedding was created.
   */
  @CreationTimestamp
  @Column(nullable = false)
  private Instant createdAt;

  /**
   * Version of the embedding (for tracking model upgrades).
   */
  @Column(nullable = false)
  @Builder.Default
  private Integer version = 1;
}
