global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: threadly-core
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["threadly-core:8080"]

  - job_name: threadly-ai
    metrics_path: /metrics
    static_configs:
      - targets: ["threadly-ai:8081"]

  - job_name: centrifugo
    metrics_path: /metrics
    static_configs:
      - targets: ["centrifugo:8000"]
