/**
 * DEPRECATED: Do not use hardcoded NODE_CATALOG export
 *
 * Node types are now fetched dynamically from the backend API.
 * Use the useNodeCatalog() hook from hooks/useCatalog.ts instead.
 *
 * This file is kept for backward compatibility only during migration.
 * All components should be updated to use the React Query hooks.
 */

export interface NodeCatalogEntry {
  type: string;
  label: string;
  description: string;
  icon: string; // lucide icon name
  category: "Messaging" | "Logic" | "AI" | "Integration" | "Flow Control";
  color: string; // hex for node header accent
  defaultData: Record<string, unknown>;
  inputs?: number;
  outputs?: number;
}

/**
 * @deprecated Use useNodeCatalog() from hooks/useCatalog.ts instead
 * This export is kept only for backward compatibility during migration.
 */
export const NODE_CATALOG: NodeCatalogEntry[] = [
  // Messaging (Blue)
  {
    type: "message",
    label: "Send Message",
    description: "Send text to the user",
    icon: "MessageSquare",
    category: "Messaging",
    color: "#3B82F6",
    defaultData: { content: "" },
    inputs: 1,
    outputs: 1,
  },
  {
    type: "question",
    label: "Ask Question",
    description: "Ask and capture user reply",
    icon: "HelpCircle",
    category: "Messaging",
    color: "#3B82F6",
    defaultData: { content: "", variable: "" },
    inputs: 1,
    outputs: 1,
  },
  {
    type: "collect_input",
    label: "Collect Input",
    description: "Validate and collect user input",
    icon: "FormInput",
    category: "Messaging",
    color: "#3B82F6",
    defaultData: { variable: "", validation: "none", prompt: "" },
    inputs: 1,
    outputs: 1,
  },
  {
    type: "send_email",
    label: "Send Email",
    description: "Send email to recipient",
    icon: "Mail",
    category: "Messaging",
    color: "#3B82F6",
    defaultData: { to: "", subject: "", body: "" },
    inputs: 1,
    outputs: 1,
  },
  // Logic (Purple)
  {
    type: "condition",
    label: "Condition",
    description: "Branch on variable value",
    icon: "GitBranch",
    category: "Logic",
    color: "#8B5CF6",
    defaultData: { conditions: [], logicalOperator: "AND" },
    inputs: 1,
    outputs: 2,
  },
  {
    type: "switch",
    label: "Switch",
    description: "Multi-branch on variable",
    icon: "Shuffle",
    category: "Logic",
    color: "#8B5CF6",
    defaultData: { variable: "", cases: [] },
    inputs: 1,
    outputs: 3,
  },
  {
    type: "set_variable",
    label: "Set Variable",
    description: "Set session variables",
    icon: "Variable",
    category: "Logic",
    color: "#8B5CF6",
    defaultData: { assignments: [] },
    inputs: 1,
    outputs: 1,
  },
  {
    type: "delay",
    label: "Delay",
    description: "Wait before continuing",
    icon: "Clock",
    category: "Logic",
    color: "#8B5CF6",
    defaultData: { seconds: 5 },
    inputs: 1,
    outputs: 1,
  },
  {
    type: "loop",
    label: "Loop",
    description: "Repeat action N times",
    icon: "Repeat2",
    category: "Logic",
    color: "#8B5CF6",
    defaultData: { iterations: 5, variable: "" },
    inputs: 1,
    outputs: 1,
  },
  {
    type: "subflow",
    label: "Subflow",
    description: "Call another workflow",
    icon: "Package",
    category: "Logic",
    color: "#8B5CF6",
    defaultData: { flowId: "", parameters: {} },
    inputs: 1,
    outputs: 1,
  },
  // AI (Green)
  {
    type: "ai_reply",
    label: "AI Reply",
    description: "LLM response with RAG",
    icon: "Sparkles",
    category: "AI",
    color: "#10B981",
    defaultData: {
      systemPrompt: "",
      maxTokens: 1024,
      temperature: 0.7,
      useKnowledgeBase: true,
    },
    inputs: 1,
    outputs: 1,
  },
  {
    type: "classify_intent",
    label: "Classify Intent",
    description: "Detect user intent",
    icon: "Zap",
    category: "AI",
    color: "#10B981",
    defaultData: { intents: [], model: "gpt-4" },
    inputs: 1,
    outputs: 3,
  },
  {
    type: "extract_entities",
    label: "Extract Entities",
    description: "Extract info from text",
    icon: "Target",
    category: "AI",
    color: "#10B981",
    defaultData: { entities: [], outputVariable: "" },
    inputs: 1,
    outputs: 1,
  },
  {
    type: "sentiment_analysis",
    label: "Sentiment Analysis",
    description: "Analyze emotion/sentiment",
    icon: "Smile",
    category: "AI",
    color: "#10B981",
    defaultData: { outputVariable: "sentiment", threshold: 0.5 },
    inputs: 1,
    outputs: 1,
  },
  // Integration (Amber)
  {
    type: "api_call",
    label: "HTTP Request",
    description: "Call external APIs",
    icon: "Globe",
    category: "Integration",
    color: "#F59E0B",
    defaultData: { method: "GET", url: "", headers: [], body: "" },
    inputs: 1,
    outputs: 1,
  },
  {
    type: "slack",
    label: "Slack",
    description: "Send Slack message",
    icon: "Send",
    category: "Integration",
    color: "#F59E0B",
    defaultData: { channel: "", message: "", threadTs: "" },
    inputs: 1,
    outputs: 1,
  },
  {
    type: "hubspot",
    label: "HubSpot",
    description: "Create/update HubSpot contact",
    icon: "Database",
    category: "Integration",
    color: "#F59E0B",
    defaultData: { action: "create", properties: {} },
    inputs: 1,
    outputs: 1,
  },
  {
    type: "google_sheets",
    label: "Google Sheets",
    description: "Append row to sheet",
    icon: "Sheet",
    category: "Integration",
    color: "#F59E0B",
    defaultData: { spreadsheetId: "", sheetName: "", values: [] },
    inputs: 1,
    outputs: 1,
  },
  {
    type: "twilio",
    label: "Twilio SMS",
    description: "Send SMS via Twilio",
    icon: "MessageCircle",
    category: "Integration",
    color: "#F59E0B",
    defaultData: { to: "", message: "" },
    inputs: 1,
    outputs: 1,
  },
  {
    type: "notion",
    label: "Notion",
    description: "Create Notion page/database entry",
    icon: "FileText",
    category: "Integration",
    color: "#F59E0B",
    defaultData: { databaseId: "", properties: {} },
    inputs: 1,
    outputs: 1,
  },
  // Flow Control (Red)
  {
    type: "handoff",
    label: "Human Handoff",
    description: "Transfer to human agent",
    icon: "UserCheck",
    category: "Flow Control",
    color: "#EF4444",
    defaultData: { message: "Connecting you to a human agent..." },
    inputs: 1,
    outputs: 1,
  },
  {
    type: "end",
    label: "End Flow",
    description: "End the conversation",
    icon: "StopCircle",
    category: "Flow Control",
    color: "#EF4444",
    defaultData: { message: "" },
    inputs: 1,
    outputs: 0,
  },
  {
    type: "cron_trigger",
    label: "Cron Trigger",
    description: "Schedule workflow on interval",
    icon: "Timer",
    category: "Flow Control",
    color: "#EF4444",
    defaultData: { cronExpression: "0 9 * * *", timezone: "UTC" },
    inputs: 0,
    outputs: 1,
  },
  {
    type: "webhook_trigger",
    label: "Webhook Trigger",
    description: "Trigger on webhook call",
    icon: "Webhook",
    category: "Flow Control",
    color: "#EF4444",
    defaultData: { path: "", method: "POST" },
    inputs: 0,
    outputs: 1,
  },
  {
    type: "error_branch",
    label: "Error Handler",
    description: "Handle errors in flow",
    icon: "AlertTriangle",
    category: "Flow Control",
    color: "#EF4444",
    defaultData: { errorTypes: [] },
    inputs: 1,
    outputs: 2,
  },
];

export const CATEGORY_ORDER = [
  "Messaging",
  "Logic",
  "AI",
  "Integration",
  "Flow Control",
] as const;
