import type { FlowDefinition } from "./types"

export interface Template {
  id: string
  name: string
  description: string
  category: "Support" | "LeadGen" | "Ecommerce" | "Healthcare" | "RealEstate" | "Education" | "HR"
  nodeCount: number
  definition: FlowDefinition
  avatar?: string
}

export const TEMPLATES: Template[] = [
  {
    id: "customer-support",
    name: "Customer Support",
    description: "Handle common support questions with escalation to humans",
    category: "Support",
    nodeCount: 8,
    avatar: "🎧",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 150 },
          data: { content: "Hello! How can I help you today?" },
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 250 },
          data: { content: "What is your issue?", variable: "issue" },
        },
        {
          id: "ai_1",
          type: "ai_reply",
          position: { x: 300, y: 350 },
          data: {
            systemPrompt: "You are a helpful customer support agent",
            maxTokens: 512,
            temperature: 0.7,
            useKnowledgeBase: true,
          },
        },
        {
          id: "condition_1",
          type: "condition",
          position: { x: 300, y: 450 },
          data: { conditions: [], logicalOperator: "AND" },
        },
        {
          id: "msg_2",
          type: "message",
          position: { x: 100, y: 550 },
          data: { content: "Is there anything else I can help you with?" },
        },
        {
          id: "handoff_1",
          type: "handoff",
          position: { x: 500, y: 550 },
          data: { message: "Connecting you to an agent..." },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 650 },
          data: { message: "Thank you for contacting us!" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "msg_1" },
        { id: "e2", source: "msg_1", target: "question_1" },
        { id: "e3", source: "question_1", target: "ai_1" },
        { id: "e4", source: "ai_1", target: "condition_1" },
        { id: "e5", source: "condition_1", target: "msg_2", sourceHandle: "true" },
        { id: "e6", source: "condition_1", target: "handoff_1", sourceHandle: "false" },
        { id: "e7", source: "msg_2", target: "end_1" },
        { id: "e8", source: "handoff_1", target: "end_1" },
      ],
    },
  },
  {
    id: "lead-qualification",
    name: "Lead Qualification",
    description: "Automatically qualify leads and score them",
    category: "LeadGen",
    nodeCount: 7,
    avatar: "📊",
    definition: {
      nodes: [
        {
          id: "webhook_1",
          type: "webhook_trigger",
          position: { x: 300, y: 60 },
          data: { path: "/leads", method: "POST" },
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 150 },
          data: { content: "What is your budget?", variable: "budget" },
        },
        {
          id: "question_2",
          type: "question",
          position: { x: 300, y: 250 },
          data: { content: "What is your timeline?", variable: "timeline" },
        },
        {
          id: "ai_1",
          type: "classify_intent",
          position: { x: 300, y: 350 },
          data: { intents: ["High Interest", "Medium Interest", "Low Interest"], model: "gpt-4" },
        },
        {
          id: "api_1",
          type: "api_call",
          position: { x: 300, y: 450 },
          data: { method: "POST", url: "https://crm.example.com/leads", headers: [], body: "" },
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 550 },
          data: { content: "Thanks! We'll review your info and get back to you soon." },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 650 },
          data: { message: "" },
        },
      ],
      edges: [
        { id: "e1", source: "webhook_1", target: "question_1" },
        { id: "e2", source: "question_1", target: "question_2" },
        { id: "e3", source: "question_2", target: "ai_1" },
        { id: "e4", source: "ai_1", target: "api_1" },
        { id: "e5", source: "api_1", target: "msg_1" },
        { id: "e6", source: "msg_1", target: "end_1" },
      ],
    },
  },
  {
    id: "ecommerce-order-status",
    name: "E-commerce Order Status",
    description: "Track and update customers on their order status",
    category: "Ecommerce",
    nodeCount: 6,
    avatar: "📦",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 150 },
          data: { content: "What is your order number?", variable: "order_id" },
        },
        {
          id: "api_1",
          type: "api_call",
          position: { x: 300, y: 250 },
          data: {
            method: "GET",
            url: "https://api.shopify.com/orders",
            headers: [],
            body: "",
          },
        },
        {
          id: "ai_1",
          type: "ai_reply",
          position: { x: 300, y: 350 },
          data: {
            systemPrompt: "Format order status as a friendly message",
            maxTokens: 256,
            temperature: 0.5,
            useKnowledgeBase: false,
          },
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 450 },
          data: { content: "" },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 550 },
          data: { message: "" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "question_1" },
        { id: "e2", source: "question_1", target: "api_1" },
        { id: "e3", source: "api_1", target: "ai_1" },
        { id: "e4", source: "ai_1", target: "msg_1" },
        { id: "e5", source: "msg_1", target: "end_1" },
      ],
    },
  },
  {
    id: "healthcare-appointment",
    name: "Healthcare Appointment",
    description: "Schedule and confirm healthcare appointments",
    category: "Healthcare",
    nodeCount: 8,
    avatar: "🏥",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 150 },
          data: { content: "Welcome to our appointment booking system" },
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 250 },
          data: { content: "What type of appointment?", variable: "appointment_type" },
        },
        {
          id: "question_2",
          type: "question",
          position: { x: 300, y: 350 },
          data: { content: "What date works best?", variable: "date" },
        },
        {
          id: "question_3",
          type: "question",
          position: { x: 300, y: 450 },
          data: { content: "What time?", variable: "time" },
        },
        {
          id: "api_1",
          type: "api_call",
          position: { x: 300, y: 550 },
          data: { method: "POST", url: "https://health.example.com/appointments", headers: [], body: "" },
        },
        {
          id: "msg_2",
          type: "message",
          position: { x: 300, y: 650 },
          data: { content: "Your appointment has been confirmed!" },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 750 },
          data: { message: "" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "msg_1" },
        { id: "e2", source: "msg_1", target: "question_1" },
        { id: "e3", source: "question_1", target: "question_2" },
        { id: "e4", source: "question_2", target: "question_3" },
        { id: "e5", source: "question_3", target: "api_1" },
        { id: "e6", source: "api_1", target: "msg_2" },
        { id: "e7", source: "msg_2", target: "end_1" },
      ],
    },
  },
  {
    id: "real-estate-inquiry",
    name: "Real Estate Inquiry",
    description: "Qualify real estate leads and schedule viewings",
    category: "RealEstate",
    nodeCount: 7,
    avatar: "🏠",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 150 },
          data: { content: "Thank you for your interest in our properties!" },
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 250 },
          data: { content: "What type of property are you looking for?", variable: "property_type" },
        },
        {
          id: "question_2",
          type: "question",
          position: { x: 300, y: 350 },
          data: { content: "What is your budget range?", variable: "budget" },
        },
        {
          id: "hubspot_1",
          type: "hubspot",
          position: { x: 300, y: 450 },
          data: { action: "create", properties: {} },
        },
        {
          id: "msg_2",
          type: "message",
          position: { x: 300, y: 550 },
          data: { content: "I'll connect you with an agent soon!" },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 650 },
          data: { message: "" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "msg_1" },
        { id: "e2", source: "msg_1", target: "question_1" },
        { id: "e3", source: "question_1", target: "question_2" },
        { id: "e4", source: "question_2", target: "hubspot_1" },
        { id: "e5", source: "hubspot_1", target: "msg_2" },
        { id: "e6", source: "msg_2", target: "end_1" },
      ],
    },
  },
  {
    id: "job-screener",
    name: "Job Screener",
    description: "Screen job applicants with automated questions",
    category: "Education",
    nodeCount: 6,
    avatar: "💼",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 150 },
          data: { content: "Welcome to our screening process!" },
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 250 },
          data: { content: "How many years of experience do you have?", variable: "experience" },
        },
        {
          id: "question_2",
          type: "question",
          position: { x: 300, y: 350 },
          data: { content: "Are you available to start immediately?", variable: "availability" },
        },
        {
          id: "msg_2",
          type: "message",
          position: { x: 300, y: 450 },
          data: { content: "Thank you! We'll review your application and get back to you soon." },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 550 },
          data: { message: "" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "msg_1" },
        { id: "e2", source: "msg_1", target: "question_1" },
        { id: "e3", source: "question_1", target: "question_2" },
        { id: "e4", source: "question_2", target: "msg_2" },
        { id: "e5", source: "msg_2", target: "end_1" },
      ],
    },
  },
  {
    id: "restaurant-reservation",
    name: "Restaurant Reservation",
    description: "Manage restaurant reservations and check availability",
    category: "Ecommerce",
    nodeCount: 7,
    avatar: "🍽️",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 150 },
          data: { content: "Welcome to our reservation system!" },
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 250 },
          data: { content: "How many guests?", variable: "guests" },
        },
        {
          id: "question_2",
          type: "question",
          position: { x: 300, y: 350 },
          data: { content: "What date and time?", variable: "datetime" },
        },
        {
          id: "api_1",
          type: "api_call",
          position: { x: 300, y: 450 },
          data: { method: "POST", url: "https://reserve.example.com/book", headers: [], body: "" },
        },
        {
          id: "msg_2",
          type: "message",
          position: { x: 300, y: 550 },
          data: { content: "Your reservation is confirmed!" },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 650 },
          data: { message: "" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "msg_1" },
        { id: "e2", source: "msg_1", target: "question_1" },
        { id: "e3", source: "question_1", target: "question_2" },
        { id: "e4", source: "question_2", target: "api_1" },
        { id: "e5", source: "api_1", target: "msg_2" },
        { id: "e6", source: "msg_2", target: "end_1" },
      ],
    },
  },
  {
    id: "product-recommendation",
    name: "Product Recommendation",
    description: "Recommend products based on user preferences",
    category: "Ecommerce",
    nodeCount: 5,
    avatar: "🛍️",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 150 },
          data: { content: "What are you looking for?", variable: "search_query" },
        },
        {
          id: "ai_1",
          type: "ai_reply",
          position: { x: 300, y: 250 },
          data: {
            systemPrompt: "You are a product recommendation specialist",
            maxTokens: 256,
            temperature: 0.7,
            useKnowledgeBase: true,
          },
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 350 },
          data: { content: "Here are my recommendations" },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 450 },
          data: { message: "" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "question_1" },
        { id: "e2", source: "question_1", target: "ai_1" },
        { id: "e3", source: "ai_1", target: "msg_1" },
        { id: "e4", source: "msg_1", target: "end_1" },
      ],
    },
  },
  {
    id: "employee-onboarding",
    name: "Employee Onboarding",
    description: "Streamline new employee onboarding process",
    category: "HR",
    nodeCount: 8,
    avatar: "👨‍💼",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 150 },
          data: { content: "Welcome to the team!" },
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 250 },
          data: { content: "What is your department?", variable: "department" },
        },
        {
          id: "question_2",
          type: "question",
          position: { x: 300, y: 350 },
          data: { content: "What is your manager's name?", variable: "manager" },
        },
        {
          id: "api_1",
          type: "api_call",
          position: { x: 300, y: 450 },
          data: {
            method: "POST",
            url: "https://hr.example.com/onboard",
            headers: [],
            body: "",
          },
        },
        {
          id: "msg_2",
          type: "message",
          position: { x: 300, y: 550 },
          data: { content: "Your onboarding has been initiated" },
        },
        {
          id: "msg_3",
          type: "message",
          position: { x: 300, y: 650 },
          data: { content: "You'll receive setup instructions shortly" },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 750 },
          data: { message: "" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "msg_1" },
        { id: "e2", source: "msg_1", target: "question_1" },
        { id: "e3", source: "question_1", target: "question_2" },
        { id: "e4", source: "question_2", target: "api_1" },
        { id: "e5", source: "api_1", target: "msg_2" },
        { id: "e6", source: "msg_2", target: "msg_3" },
        { id: "e7", source: "msg_3", target: "end_1" },
      ],
    },
  },
  {
    id: "event-registration",
    name: "Event Registration",
    description: "Register attendees for events and send confirmations",
    category: "Support",
    nodeCount: 6,
    avatar: "🎫",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 150 },
          data: { content: "Register for our upcoming event!" },
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 250 },
          data: { content: "What is your full name?", variable: "name" },
        },
        {
          id: "question_2",
          type: "question",
          position: { x: 300, y: 350 },
          data: { content: "What is your email?", variable: "email" },
        },
        {
          id: "api_1",
          type: "api_call",
          position: { x: 300, y: 450 },
          data: {
            method: "POST",
            url: "https://events.example.com/register",
            headers: [],
            body: "",
          },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 550 },
          data: { message: "Thank you for registering!" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "msg_1" },
        { id: "e2", source: "msg_1", target: "question_1" },
        { id: "e3", source: "question_1", target: "question_2" },
        { id: "e4", source: "question_2", target: "api_1" },
        { id: "e5", source: "api_1", target: "end_1" },
      ],
    },
  },
  {
    id: "feedback-collection",
    name: "Feedback Collection",
    description: "Collect structured feedback from customers",
    category: "Support",
    nodeCount: 5,
    avatar: "📝",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 150 },
          data: { content: "We'd love your feedback!" },
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 250 },
          data: { content: "How would you rate your experience?", variable: "rating" },
        },
        {
          id: "question_2",
          type: "question",
          position: { x: 300, y: 350 },
          data: { content: "Any additional comments?", variable: "comments" },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 450 },
          data: { message: "Thank you for your feedback!" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "msg_1" },
        { id: "e2", source: "msg_1", target: "question_1" },
        { id: "e3", source: "question_1", target: "question_2" },
        { id: "e4", source: "question_2", target: "end_1" },
      ],
    },
  },
  {
    id: "abandoned-cart",
    name: "Abandoned Cart",
    description: "Re-engage customers with abandoned carts",
    category: "Ecommerce",
    nodeCount: 5,
    avatar: "🛒",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 150 },
          data: { content: "You left something in your cart!" },
        },
        {
          id: "msg_2",
          type: "message",
          position: { x: 300, y: 250 },
          data: { content: "Would you like to complete your purchase?" },
        },
        {
          id: "api_1",
          type: "api_call",
          position: { x: 300, y: 350 },
          data: {
            method: "POST",
            url: "https://shop.example.com/recover-cart",
            headers: [],
            body: "",
          },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 450 },
          data: { message: "" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "msg_1" },
        { id: "e2", source: "msg_1", target: "msg_2" },
        { id: "e3", source: "msg_2", target: "api_1" },
        { id: "e4", source: "api_1", target: "end_1" },
      ],
    },
  },
  {
    id: "saas-trial",
    name: "SaaS Trial Signup",
    description: "Onboard users to free trial with walkthrough",
    category: "Support",
    nodeCount: 6,
    avatar: "🚀",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 150 },
          data: { content: "Welcome to our 14-day free trial!" },
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 250 },
          data: { content: "What's your company size?", variable: "company_size" },
        },
        {
          id: "question_2",
          type: "question",
          position: { x: 300, y: 350 },
          data: { content: "What's your main use case?", variable: "use_case" },
        },
        {
          id: "msg_2",
          type: "message",
          position: { x: 300, y: 450 },
          data: { content: "Let me set up your workspace and send you a guide" },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 550 },
          data: { message: "" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "msg_1" },
        { id: "e2", source: "msg_1", target: "question_1" },
        { id: "e3", source: "question_1", target: "question_2" },
        { id: "e4", source: "question_2", target: "msg_2" },
        { id: "e5", source: "msg_2", target: "end_1" },
      ],
    },
  },
  {
    id: "technical-support",
    name: "Technical Support",
    description: "Troubleshoot technical issues with flowchart logic",
    category: "Support",
    nodeCount: 7,
    avatar: "🔧",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 150 },
          data: { content: "Let's troubleshoot the issue" },
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 250 },
          data: { content: "What error are you seeing?", variable: "error" },
        },
        {
          id: "condition_1",
          type: "condition",
          position: { x: 300, y: 350 },
          data: { conditions: [], logicalOperator: "AND" },
        },
        {
          id: "msg_2",
          type: "message",
          position: { x: 100, y: 450 },
          data: { content: "Try these steps..." },
        },
        {
          id: "handoff_1",
          type: "handoff",
          position: { x: 500, y: 450 },
          data: { message: "Connecting to technical team..." },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 550 },
          data: { message: "" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "msg_1" },
        { id: "e2", source: "msg_1", target: "question_1" },
        { id: "e3", source: "question_1", target: "condition_1" },
        { id: "e4", source: "condition_1", target: "msg_2", sourceHandle: "true" },
        { id: "e5", source: "condition_1", target: "handoff_1", sourceHandle: "false" },
        { id: "e6", source: "msg_2", target: "end_1" },
        { id: "e7", source: "handoff_1", target: "end_1" },
      ],
    },
  },
  {
    id: "insurance-quote",
    name: "Insurance Quote",
    description: "Generate personalized insurance quotes",
    category: "Healthcare",
    nodeCount: 6,
    avatar: "🛡️",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 150 },
          data: { content: "Get your personalized insurance quote" },
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 250 },
          data: { content: "What type of coverage?", variable: "coverage_type" },
        },
        {
          id: "api_1",
          type: "api_call",
          position: { x: 300, y: 350 },
          data: {
            method: "POST",
            url: "https://insurance.example.com/quote",
            headers: [],
            body: "",
          },
        },
        {
          id: "msg_2",
          type: "message",
          position: { x: 300, y: 450 },
          data: { content: "Here's your personalized quote" },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 550 },
          data: { message: "" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "msg_1" },
        { id: "e2", source: "msg_1", target: "question_1" },
        { id: "e3", source: "question_1", target: "api_1" },
        { id: "e4", source: "api_1", target: "msg_2" },
        { id: "e5", source: "msg_2", target: "end_1" },
      ],
    },
  },
  {
    id: "gym-inquiry",
    name: "Gym Membership Inquiry",
    description: "Handle gym membership inquiries and sign-ups",
    category: "Support",
    nodeCount: 6,
    avatar: "💪",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 150 },
          data: { content: "Welcome to our gym!" },
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 250 },
          data: { content: "What type of membership interests you?", variable: "membership_type" },
        },
        {
          id: "api_1",
          type: "api_call",
          position: { x: 300, y: 350 },
          data: {
            method: "POST",
            url: "https://gym.example.com/inquiry",
            headers: [],
            body: "",
          },
        },
        {
          id: "msg_2",
          type: "message",
          position: { x: 300, y: 450 },
          data: { content: "We'll contact you with details soon" },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 550 },
          data: { message: "" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "msg_1" },
        { id: "e2", source: "msg_1", target: "question_1" },
        { id: "e3", source: "question_1", target: "api_1" },
        { id: "e4", source: "api_1", target: "msg_2" },
        { id: "e5", source: "msg_2", target: "end_1" },
      ],
    },
  },
  {
    id: "language-tutor",
    name: "Language Tutor",
    description: "Interactive language learning lessons",
    category: "Education",
    nodeCount: 5,
    avatar: "📚",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 150 },
          data: { content: "Let's practice together!" },
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 250 },
          data: { content: "What would you like to say?", variable: "user_input" },
        },
        {
          id: "ai_1",
          type: "ai_reply",
          position: { x: 300, y: 350 },
          data: {
            systemPrompt: "You are a language tutor. Correct and provide feedback",
            maxTokens: 256,
            temperature: 0.7,
            useKnowledgeBase: false,
          },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 450 },
          data: { message: "Great job! Practice more anytime" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "msg_1" },
        { id: "e2", source: "msg_1", target: "question_1" },
        { id: "e3", source: "question_1", target: "ai_1" },
        { id: "e4", source: "ai_1", target: "end_1" },
      ],
    },
  },
  {
    id: "travel-booking",
    name: "Travel Booking",
    description: "Book flights and hotels with personalized recommendations",
    category: "Ecommerce",
    nodeCount: 7,
    avatar: "✈️",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 150 },
          data: { content: "Plan your perfect trip!" },
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 250 },
          data: { content: "Where are you going?", variable: "destination" },
        },
        {
          id: "question_2",
          type: "question",
          position: { x: 300, y: 350 },
          data: { content: "When are you traveling?", variable: "dates" },
        },
        {
          id: "api_1",
          type: "api_call",
          position: { x: 300, y: 450 },
          data: {
            method: "GET",
            url: "https://travel.example.com/search",
            headers: [],
            body: "",
          },
        },
        {
          id: "msg_2",
          type: "message",
          position: { x: 300, y: 550 },
          data: { content: "Here are the best options for your trip" },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 650 },
          data: { message: "" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "msg_1" },
        { id: "e2", source: "msg_1", target: "question_1" },
        { id: "e3", source: "question_1", target: "question_2" },
        { id: "e4", source: "question_2", target: "api_1" },
        { id: "e5", source: "api_1", target: "msg_2" },
        { id: "e6", source: "msg_2", target: "end_1" },
      ],
    },
  },
  {
    id: "legal-faq",
    name: "Legal FAQ Bot",
    description: "Answer legal questions with knowledge base",
    category: "Support",
    nodeCount: 4,
    avatar: "⚖️",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 150 },
          data: { content: "What legal question can I help with?", variable: "question" },
        },
        {
          id: "ai_1",
          type: "ai_reply",
          position: { x: 300, y: 250 },
          data: {
            systemPrompt: "You are a legal assistant. Provide helpful information",
            maxTokens: 512,
            temperature: 0.3,
            useKnowledgeBase: true,
          },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 350 },
          data: { message: "For more help, contact our legal team" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "question_1" },
        { id: "e2", source: "question_1", target: "ai_1" },
        { id: "e3", source: "ai_1", target: "end_1" },
      ],
    },
  },
  {
    id: "b2b-sales-qualifier",
    name: "B2B Sales Qualifier",
    description: "Qualify enterprise sales leads with detailed questions",
    category: "LeadGen",
    nodeCount: 8,
    avatar: "📈",
    definition: {
      nodes: [
        {
          id: "start_1",
          type: "start",
          position: { x: 300, y: 60 },
          data: {},
        },
        {
          id: "msg_1",
          type: "message",
          position: { x: 300, y: 150 },
          data: { content: "Let's explore how we can help your business" },
        },
        {
          id: "question_1",
          type: "question",
          position: { x: 300, y: 250 },
          data: { content: "What's your company?", variable: "company" },
        },
        {
          id: "question_2",
          type: "question",
          position: { x: 300, y: 350 },
          data: { content: "What's your biggest challenge?", variable: "challenge" },
        },
        {
          id: "question_3",
          type: "question",
          position: { x: 300, y: 450 },
          data: { content: "What's your budget range?", variable: "budget" },
        },
        {
          id: "api_1",
          type: "api_call",
          position: { x: 300, y: 550 },
          data: {
            method: "POST",
            url: "https://crm.example.com/leads",
            headers: [],
            body: "",
          },
        },
        {
          id: "msg_2",
          type: "message",
          position: { x: 300, y: 650 },
          data: { content: "A sales rep will reach out within 24 hours" },
        },
        {
          id: "end_1",
          type: "end",
          position: { x: 300, y: 750 },
          data: { message: "" },
        },
      ],
      edges: [
        { id: "e1", source: "start_1", target: "msg_1" },
        { id: "e2", source: "msg_1", target: "question_1" },
        { id: "e3", source: "question_1", target: "question_2" },
        { id: "e4", source: "question_2", target: "question_3" },
        { id: "e5", source: "question_3", target: "api_1" },
        { id: "e6", source: "api_1", target: "msg_2" },
        { id: "e7", source: "msg_2", target: "end_1" },
      ],
    },
  },
]

export const TEMPLATE_CATEGORIES = [
  "All",
  "Support",
  "LeadGen",
  "Ecommerce",
  "Healthcare",
  "RealEstate",
  "Education",
  "HR",
] as const
