name = "threadly-widget-cdn"
main = "widget-worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "WIDGET_BUCKET"
bucket_name = "threadly-widget"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.r2_buckets]]
binding = "WIDGET_BUCKET"
bucket_name = "threadly-widget"
